apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minitalk
  namespace: argocd
  labels:
    app: minitalk
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: file:///Users/jeeon-park/Documents/DEV/observability/minitalk
    targetRevision: HEAD
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: minitalk
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
  revisionHistoryLimit: 10 
