apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../base

namePrefix: dev-

labels:
- includeSelectors: true
  pairs:
  env: dev

patches:
- path: replica-patch.yaml

images:
- name: minitalk-backend
  newTag: latest
- name: minitalk-frontend
  newTag: latest 
