apiVersion: apps/v1
kind: Deployment
metadata:
  name: minitalk-backend
  namespace: minitalk
  labels:
    app: minitalk-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minitalk-backend
  template:
    metadata:
      labels:
        app: minitalk-backend
    spec:
      containers:
      - name: backend
        image: minitalk-backend:latest
        imagePullPolicy: Never  # For kind cluster
        ports:
        - containerPort: 4000
        env:
        - name: PORT
          value: "4000"
        - name: JWT_SECRET
          value: "your-secret-key-change-in-production"
        - name: NODE_ENV
          value: "production"
        resources:
          requests:
            memory: "1Gi"
            cpu: "1000m"
          limits:
            memory: "24Gi"
            cpu: "8000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: data-storage
          mountPath: /app/data/storage
      volumes:
      - name: data-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: minitalk-backend-service
  namespace: minitalk
  labels:
    app: minitalk-backend
spec:
  selector:
    app: minitalk-backend
  ports:
  - port: 4000
    targetPort: 4000
    protocol: TCP
  type: ClusterIP 
