apiVersion: apps/v1
kind: Deployment
metadata:
  name: minitalk-backend
  namespace: jonny
  labels:
    app: minitalk-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minitalk-backend
  template:
    metadata:
      labels:
        app: minitalk-backend
    spec:
      containers:
      - name: backend
        image: ghcr.io/jeeonpark/minitalk-backend:main-otlp-debug-v1
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        env:
        - name: PORT
          value: "4000"
        - name: JWT_SECRET
          value: "your-secret-key-change-in-production"
        - name: NODE_ENV
          value: "production"
        # OpenTelemetry OTLP environment variables
        - name: OTEL_SERVICE_NAME
          value: "minitalk-backend"
        - name: OTEL_SERVICE_VERSION
          value: "1.0.1"
        - name: OTEL_SERVICE_NAMESPACE
          value: "jonny"
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: "service.name=minitalk-backend,service.version=1.0.1,service.namespace=jonny,deployment.environment=production"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://datadog-agent.monitoring.svc.cluster.local:4317"
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: "http://datadog-agent.monitoring.svc.cluster.local:4317"
        - name: OTEL_EXPORTER_OTLP_PROTOCOL
          value: "grpc"
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
        - name: OTEL_TRACES_SAMPLER
          value: "always_on"
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "2Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: data-storage
          mountPath: /app/data/storage
      volumes:
      - name: data-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: minitalk-backend-service
  namespace: jonny
  labels:
    app: minitalk-backend
spec:
  selector:
    app: minitalk-backend
  ports:
  - port: 4000
    targetPort: 4000
    protocol: TCP
  type: ClusterIP 
