apiVersion: apps/v1
kind: Deployment
metadata:
  name: minitalk-backend
spec:
  template:
    metadata:
      labels:
        app: minitalk-backend
        app.kubernetes.io/name: minitalk
        app.kubernetes.io/version: v1.0.0
    spec:
      containers:
      - name: backend
        image: ghcr.io/jeeonpark/observability-minitalk/minitalk-backend:main-fix-mongo-final
        imagePullPolicy: Always
        ports:
        - containerPort: 4000
        env:
        - name: NODE_ENV
          value: "production"
        - name: MONGODB_URI
          value: "mongodb://$(MONGODB_USERNAME):$(MONGODB_PASSWORD)@mongodb:27017/minitalk?authSource=admin"
        - name: MONGODB_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongodb-secrets
              key: username
        - name: MONGODB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongodb-secrets
              key: password
        - name: JWT_SECRET
          value: null
          valueFrom:
            secretKeyRef:
              name: minitalk-secrets
              key: jwt-secret
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_ENV
          value: "production"
        - name: DD_SERVICE
          value: "minitalk-backend"
        - name: DD_VERSION
          value: "1.0.0"
        - name: DD_TRACE_ENABLED
          value: "true"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 4000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 4000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: minitalk-backend
  labels:
    app: minitalk-backend
    app.kubernetes.io/name: minitalk
    app.kubernetes.io/version: v1.0.0
spec:
  selector:
    app: minitalk-backend
    app.kubernetes.io/name: minitalk
    app.kubernetes.io/version: v1.0.0
  ports:
  - name: http
    port: 4000
    targetPort: 4000
    protocol: TCP
  type: ClusterIP
 
 