apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- mongodb.yaml
- backend.yaml
- frontend.yaml

commonLabels:
  app.kubernetes.io/name: minitalk
  app.kubernetes.io/version: "1.0.0"

namespace: minitalk 
