apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namePrefix: dev-

commonLabels:
  env: dev

patchesStrategicMerge:
- replica-patch.yaml

images:
- name: minitalk-backend
  newTag: latest
- name: minitalk-frontend
  newTag: latest 
